### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by krober10nd** [HakanSeven12/Delaunator-Python#2]
Hey all, Thanks for the useful program! Do the input point sets need to be integers for the code to be optimally performant? I'm thinking of using this routine in a Lloyd smoothing/mesh generation code written in Python, but it requires float points for the point sites.

Overall, is the performance anticipated to be similar to that of the javascript implementation?

Thanks.

**Comment by HakanSeven12** [comment]
I didn't compare with javascript implementation but you can see comparison result between python alternatives.

![delauny_comparison](https://user-images.githubusercontent.com/3831435/76827861-cc170100-6830-11ea-868e-9cb5893d8543.png)

**Comment by krober10nd** [comment]
Cool thank you. So the way this works is it creates a scan triangulation then files interior edges to achieve Del.-hood?

**Comment by HakanSeven12** [comment]
What is del hood?

**Comment by krober10nd** [comment]
Delaunayhood is the condition that is met when a triangulation is Delaunay.

**Comment by HakanSeven12** [comment]
Okay. It takes 3 point near the point group center, then sort other points by distance to seed and start to add triangles along the hull.
