### ISSUE TITLE
ask for advice

### ISSUE THREAD

**Issue by zcdliuwei** [HakanSeven12/Delaunator-Python#3]
What an interesting show！ And I'd like to ask，how to use your code to triangulate an image ?
thank you

**Comment by HakanSeven12** [comment]
I don't have any idea about image triangulation. But I saw some repo about that. Maybe you can take a look at them.

https://github.com/MauriceGit/Delaunay_Triangulation

**Comment by zcdliuwei** [comment]
> I don't have any idea about image triangulation. But I saw some repo about that. Maybe you can take a look at them.
> 
> https://github.com/MauriceGit/Delaunay_Triangulation

Thank you for your prompt reply. It is very helpful

**Comment by HakanSeven12** [comment]
You are welcome.
