### ISSUE TITLE
Divide by Zero (again)

### ISSUE THREAD

**Issue by StormSurge95** [HakanSeven12/Delaunator-Python#6]
So, like others, I've been experiencing a divide by zero error in the `circumradius` function; however, it's not due to duplicate points.

My error is due to a set of three points that are in a straight line with each other.

The points in particular that are causing my error are: `(137, 525)`, `(137, 509)`, and `(137, 392)`.

**Comment by StormSurge95** [comment]
Upon further investigation, this happens because in `js`, divide by zero results in `infinity`; whereas in `python`, it results in an error.

Some form of try/except may be enough to fix the issue; but I'm not sure what to make the default value.

**Comment by StormSurge95** [comment]
proposed solution:
```py
def circumradius(ax, ay, bx, by, cx, cy):
    dx = bx - ax
    dy = by - ay
    ex = cx - ax
    ey = cy - ay

    bl = dx * dx + dy * dy
    cl = ex * ex + ey * ey
    try:
        d = 0.5 / (dx * ey - dy * ex)
    except Exception:
        d = float('inf')
    x = (ey * bl - dy * cl) * d
    y = (dx * cl - ex * bl) * d
    return x * x + y * y
```

**Comment by HakanSeven12** [comment]
Thanks for solution. Can you make a pull request?

**Comment by StormSurge95** [comment]
Had to learn how as this was my first pull request. lol But a pull request has now been made.
